repos:

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
    -   id: black-jupyter
        name: format python code with black
        args:
        - --line-length
        - "100"

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=500']

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
    -   id: ruff
        files: '^.*\.py$'
        args:
        - "--config"
        - "pyproject.toml"
        - "--fix"
        - "--exit-non-zero-on-fix"


ci:
    autofix_prs: true
    autoupdate_schedule: quarterly
    autoupdate_commit_msg: "chore: pre-commit autoupdate"
