# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  # This workflow works, but is a bit of a waste of resources to trigger on every push.
  # Indeed the server doesn't need re-deploying every time the code changes,
  # because it's small and we usually don't make edits to it.
  # So it's availaible only for manual triggering in the Actions tab of github.
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
